### ISSUE TITLE
Postgres read-replicas helm templates

### ISSUE THREAD

**Issue by bryanchriswhite** [fetchai/ledger-subquery#128]
## Background

To establish a "fair" baseline to which to compare cockroach DB load testing results, we'll want to have the same number of nodes available for reading as in the cockroach cluster. 

## Acceptance criteria

We can run a variable number of postgres read-replicas in the ledger-subquery helm chart.

**Comment by amit-solanki** [comment]
PR: https://github.com/fetchai/ledger-subquery/issues/128
