### ISSUE TITLE
Strip contract bytecode from Message

### ISSUE THREAD

**Issue by bryanchriswhite** [fetchai/ledger-subquery#146]
## Background

It seems to me that contract bytecode might represent some low hanging fruit in the context of minimizing size on disk. In previous research efforts it seemed to become apparent that the bytecode doesn't expose anything useful from the indexer's perspective. I think it also stands to reason that so long as the indexer's list of use cases doesn't include distributing bytecode, there would be no other reason to have the indexer store it. In the event that someone actually did need to retrieve the bytecode as stored on chain, they can always do that that via the RPC (or CLI).

**Comment by Jonathansumner** [comment]
**Update**

Due to hurdles in the inclusion of DB migration, this issue was pushed back as part of sprint 11.
