### ISSUE TITLE
SubQuery node internal error

### ISSUE THREAD

**Issue by bryanchriswhite** [fetchai/ledger-subquery#171]
## Background

The GQL API returns an error similar to the following for all queries:
```
{
      "message": "getaddrinfo ENOTFOUND subquery-db",
      "locations": [
        {
          "line": 36,
          "column": 3
        }
      ],
      "path": [
        "blocks"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "errno": -3008,
          "code": "ENOTFOUND",
          "syscall": "getaddrinfo",
          "hostname": "subquery-db",
          "stacktrace": [
            "Error: getaddrinfo ENOTFOUND subquery-db",
            "    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)"
          ]
        }
      }
    },
```

Subquery node logs indicate some kind of issue connecting to the database:
```
2022-11-09 08:23:25 | 2022-11-09T07:23:24.985763273Z stdout F 2022-11-09T07:23:24.985Z <db> ERROR Unable to connect to the database SequelizeHostNotFoundError: getaddrinfo ENOTFOUND subquery-db
-- | --
```

**Comment by amit-solanki** [comment]
DB's PVC got 100% filled therefore, DB was not able to start and therefore, the error.

Solution:
- Increase PVC size and restarted DB (without need to resync from scratch)
- Example: https://serverfault.com/questions/955293/how-to-increase-disk-size-in-a-stateful-set

Suggestion:
- We should have a alerting mechanism if DB size is above certain threshold - maybe we can use metrics stored in grafana to do so
