### ISSUE TITLE
Add missing properties to cosmos block header

### ISSUE THREAD

**Issue by axshivam** [fetchai/ledger-subquery#237]
### Prerequisites

- [X] I checked the [documentation](https://docs.fetch.ai/ledger-subquery/introduction/) and made sure this feature does not already exist.
- [X] I checked the [existing issues](https://github.com/fetchai/ledger-subquery/issues) to make sure this feature has not already been requested.
- [X] I have read the [code of conduct](https://github.com/fetchai/ledger-subquery/blob/main/CODE_OF_CONDUCT.md) before creating this issue.

### Problem

We are missing few block properties for cosmos block , eg proposerAddress

Ref: https://github.com/cosmos/cosmjs/blob/33271bc51cdc865cadb647a1b7ab55d873637f39/packages/tendermint-rpc/src/tendermint34/responses.ts#L279

I have raised the same issue to Subquery Network, and they implemented it in their latest release. Now we can easily integrate.

Ref: https://github.com/subquery/subql-cosmos/pull/94

### Feature / Solution Acceptance Criteria

![Header_Cosmos](https://user-images.githubusercontent.com/36760040/215072428-3ffb387c-6466-455b-949e-2e0273f5fbcd.png)

**Comment by Jonathansumner** [comment]
Hey @axshivam, thanks for raising the issue. I will look into this for you!

**Comment by Jonathansumner** [comment]
closed with #260
