### ISSUE TITLE
Monitor sync rate

### ISSUE THREAD

**Issue by bryanchriswhite** [fetchai/ledger-subquery#76]
## Acceptance Criteria

1. We can measure the duration of time that it takes for an indexer instance to sync from the start block to the current block (at time of completion).
2. This measurement is automatically started when a preview deployment happens (i.e. a fresh indexer instance begins syncing) in any given cluster. Measurement should stop when syncing is complete.
3. These measurements are persisted somewhere and should be sufficient to show the trend of sync time across indexer versions within the same network.

### Nice to have

- We can correlate this with downtime on the subquery node.

**Comment by bryanchriswhite** [comment]
## Proposal

Perhaps we can use a k8s [Job](https://kubernetes.io/docs/concepts/workloads/controllers/job/) to run a script which queries the graphql API. I believe we already have prometheus and thanos in place such that we could transform the query response into structured log lines for integration there.

An example query:
```graphql
query syncStatus {
  blocks(first: 1, orderBy: HEIGHT_DESC) {
    totalCount
    nodes {
      id
      height
    }
  }
  transactions {
    totalCount
  }
  messages {
    totalCount
  }
  events {
    totalCount
  }
  distDelegatorClaims {
    totalCount
  }
  nativeTransfers {
    totalCount
  }
  executeContractMessages {
    totalCount
  }
  govProposalVotes {
    totalCount
  }
  legacyBridgeSwaps {
    totalCount
  }
}
```

**Comment by ayushvtf** [comment]
added cron job in sandbox cluster to collect the current hight and fetchd height on testnet and mainnet
output logs via cronjob to be visualized in Grafana via lokiQL
added both metric for testnet and mainnet
https://monitor.fetch-ai.com/d/L2IqyyV4z/subquery-indexer?orgId=1

next step is to use promethues exporter to send metrcis and have more better visuzaliztion.
